// <auto-generated />
namespace OmniScanMRI.WebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _8Mig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_8Mig));
        
        string IMigrationMetadata.Id
        {
            get { return "202310300825571_8Mig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
