// <auto-generated />
namespace OmniScanMRI.WebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _5Mig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_5Mig));
        
        string IMigrationMetadata.Id
        {
            get { return "202310280936307_5Mig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
